unionid: o1ELc6LrAZOqCjYiOZur5A-sVzYc
#unionid: oAESl0aF5qnVf6e1G7I15_QKaf8U
order_id: '20251219154324110285'
product: 趋势智投-铂金版
refund_contract: 服务终止协议-测试
# 生产：owAkH6pzIm8b-ToOmC0cz7p2IomI，仿真：o1ELc6LrAZOqCjYiOZur5A-sVzYc
blacklist:
  - "owAkH6pzIm8b-ToOmC0cz7p2IomI"
  - "o1ELc6LrAZOqCjYiOZur5A-sVzYc"
  - "owAkH6hLuQM8nATHzmdM8n-qigCg"
  - "o1ELc6C-o91OlKbgUIPaGGMgS858"
  - "oAESl0QRB8mndRVJFs69e5o8JZi0"
  - "13325171563"
  - "320324199504180352"
  - "oAESl0aF5qnVf6e1G7I15_QKaf8U"
  - "18302954019"
  - "610121199302072600"

mysql:
  host: ysjumpserver.abctougu.com
  port: 33061
  bhuser: 91605338-8d37-4ce7-afd4-17bed1154498
  password: IeXEUXeAdz5Fo24a
  database: crm.abctougu.cn

  user_sim: a45258d0-7c4f-4fbc-8993-4b9aaba75ac2
  password_sim: m4TIv93NrmWrTzAP

  user_app: fc315c68-8acc-4888-a725-ba8d15fe8283
  password_app: 3YKOatnNVHKx3UX4
  database_app: stock-rubik-cube
crm:
  #  url: https://crm.abctougu.cn
#  url: https://pay.oneil88.com/admin
  url: https://crm.blzt888.com/admin/login.html
  username: mysql
#  password: dev_test@jishubu
  password: tP1^mJ6_iL3<iU8*
  cookie:
    name: jmftou
    value: 3336e664b39602f170db2797776c35bb
  name: 赵楠
  mobile: 13325171563
  url_archives: 
    https://pay.oneil88.com/admin#/crm_v2/hegui.compliance/archives_detail.html?id=14&spm=m-204-243-245
