unionid: o1ELc6LrAZOqCjYiOZur5A-sVzYc
#unionid: oAESl0aF5qnVf6e1G7I15_QKaf8U
order_id: '20251126175948199019,20251126184350908869'
product: 趋势智投-铂金版
refund_contract: 服务终止协议-测试

mysql:
  host: ysjumpserver.abctougu.com
  port: 33061
  bhuser: 91605338-8d37-4ce7-afd4-17bed1154498
  password: IeXEUXeAdz5Fo24a
  database: crm.abctougu.cn

  user_sim: b1e036bc-5c98-4215-896a-b817af6c6eba
  password_sim: md5VLlklJTN63UC0

  user_app: c3986cad-d744-49cb-a59c-06a0888b0bec
  password_app: UT3JS2G1v10cVP9T
  database_app: stock-rubik-cube
crm:
  #  url: https://crm.abctougu.cn
#  url: https://pay.oneil88.com/admin
  url: https://crm.blzt888.com/admin/login.html
  username: mysql
#  password: dev_test@jishubu
  password: tP1^mJ6_iL3<iU8*
  cookie:
    name: jmftou
    value: 3336e664b39602f170db2797776c35bb
  name: 赵楠
  mobile: 13325171563
  url_archives: 
    https://pay.oneil88.com/admin#/crm_v2/hegui.compliance/archives_detail.html?id=14&spm=m-204-243-245
